"""001_baseline — single source of truth, generated from ORM models.

Revision ID: 001_baseline
Revises:
Create Date: 2026-05-14

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_users_email"), "auth_users", ["email"], unique=True)
    op.create_table(
        "blog_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(length=500), nullable=False),
        sa.Column("audience", sa.String(length=255), nullable=False),
        sa.Column("tone", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "PROCESSING",
                "AWAITING_OUTLINE_REVIEW",
                "AWAITING_FINAL_REVIEW",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="blogsessionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("current_stage", sa.String(length=50), nullable=True),
        sa.Column("adk_session_id", sa.String(length=255), nullable=True),
        sa.Column("invocation_id", sa.String(length=255), nullable=True),
        sa.Column("confirmation_request_id", sa.String(length=255), nullable=True),
        sa.Column("outline_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("final_content", sa.Text(), nullable=True),
        sa.Column("budget_reserved_tokens", sa.Integer(), nullable=False),
        sa.Column("budget_spent_tokens", sa.Integer(), nullable=False),
        sa.Column("budget_reserved_usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("budget_spent_usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("reap_count", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_blog_sessions_idempotency"),
    )
    op.create_index("ix_blog_sessions_status", "blog_sessions", ["status"], unique=False)
    op.create_index("ix_blog_sessions_user_id", "blog_sessions", ["user_id"], unique=False)
    op.create_table(
        "budget_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("balance_usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("reserved_usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("total_granted_usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("total_spent_usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("ix_budget_accounts_user_id", "budget_accounts", ["user_id"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("blog_session_id", sa.Integer(), nullable=False),
        sa.Column("stage_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("output_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["blog_session_id"],
            ["blog_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_runs_session", "agent_runs", ["blog_session_id"], unique=False)
    op.create_table(
        "research_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("blog_session_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["blog_session_id"],
            ["blog_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_research_sources_session", "research_sources", ["blog_session_id"], unique=False
    )
    op.create_table(
        "session_leases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("blog_session_id", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=255), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_version", sa.Integer(), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_reason", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["blog_session_id"],
            ["blog_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_session_leases_ended", "session_leases", ["ended_at"], unique=False)
    op.create_index("ix_session_leases_owner", "session_leases", ["lease_owner"], unique=False)
    op.create_index(
        "ix_session_leases_session", "session_leases", ["blog_session_id"], unique=False
    )
    op.create_index("ix_session_leases_started", "session_leases", ["started_at"], unique=False)
    op.create_table(
        "session_reservations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("blog_session_id", sa.Integer(), nullable=False),
        sa.Column("reserved_usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("reserved_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["blog_session_id"],
            ["blog_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_session_reservations_session", "session_reservations", ["blog_session_id"], unique=False
    )
    op.create_table(
        "budget_ledger",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("blog_session_id", sa.Integer(), nullable=True),
        sa.Column("agent_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "entry_type",
            sa.Enum(
                "GRANT",
                "RESERVE",
                "COMMIT",
                "RELEASE",
                "ADJUSTMENT",
                name="budgetentrytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["blog_session_id"],
            ["blog_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_budget_ledger_session", "budget_ledger", ["blog_session_id"], unique=False)
    op.create_index("ix_budget_ledger_user_id", "budget_ledger", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_budget_ledger_user_id", table_name="budget_ledger")
    op.drop_index("ix_budget_ledger_session", table_name="budget_ledger")
    op.drop_table("budget_ledger")
    op.drop_index("ix_session_reservations_user", table_name="session_reservations")
    op.drop_index("ix_session_reservations_session", table_name="session_reservations")
    op.drop_table("session_reservations")
    op.drop_index("ix_session_leases_started", table_name="session_leases")
    op.drop_index("ix_session_leases_session", table_name="session_leases")
    op.drop_index("ix_session_leases_owner", table_name="session_leases")
    op.drop_index("ix_session_leases_ended", table_name="session_leases")
    op.drop_table("session_leases")
    op.drop_index("ix_research_sources_user", table_name="research_sources")
    op.drop_index("ix_research_sources_session", table_name="research_sources")
    op.drop_table("research_sources")
    op.drop_index("ix_agent_runs_session", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_budget_accounts_user_id", table_name="budget_accounts")
    op.drop_table("budget_accounts")
    op.drop_index("ix_blog_sessions_user_id", table_name="blog_sessions")
    op.drop_index("ix_blog_sessions_status", table_name="blog_sessions")
    op.drop_table("blog_sessions")
    op.drop_index(op.f("ix_auth_users_email"), table_name="auth_users")
    op.drop_table("auth_users")
    # ### end Alembic commands ###
