"""Context compression using ADK built-in mechanisms."""

from typing import Any

from src.config.logging_config import get_logger

logger = get_logger(__name__)


class ContextCompressor:
    """
    Context compression for agent pipeline using ADK patterns.
    
    Compresses both inputs and outputs from each agent to create
    a concise context summary for the LLM judge.
    """

    def __init__(self) -> None:
        self.context_history: list[dict[str, Any]] = []

    def add_agent_context(
        self, agent_name: str, input_data: dict[str, Any], output_data: Any
    ) -> None:
        """
        Add agent's input and output to context history.
        
        Args:
            agent_name: Name of the agent
            input_data: Input provided to the agent
            output_data: Output generated by the agent
        """
        self.context_history.append(
            {
                "agent": agent_name,
                "input": input_data,
                "output": self._serialize_output(output_data),
            }
        )
        logger.info(f"context_added", agent=agent_name)

    def _serialize_output(self, output: Any) -> dict[str, Any]:
        """Serialize output to dict for compression."""
        if hasattr(output, "model_dump"):
            return output.model_dump()
        elif isinstance(output, dict):
            return output
        else:
            return {"value": str(output)}

    def compress_context(self) -> dict[str, Any]:
        """
        Compress entire context history using summarization.
        
        For MVP: Creates a structured summary
        Future: Use ADK's EventsCompactionConfig for LLM-based summarization
        
        Returns:
            Compressed context dictionary
        """
        if not self.context_history:
            return {"summary": "No context available"}

        # For now, create a structured summary
        # In production, this would use ADK's recursive summarization
        compressed = {
            "pipeline_stages": len(self.context_history),
            "agents": [ctx["agent"] for ctx in self.context_history],
            "compressed_stages": [],
        }

        for ctx in self.context_history:
            agent_name = ctx["agent"]
            compressed_stage = {
                "agent": agent_name,
                "key_inputs": self._extract_key_fields(ctx["input"]),
                "key_outputs": self._extract_key_fields(ctx["output"]),
            }
            compressed["compressed_stages"].append(compressed_stage)

        logger.info(f"context_compressed", original_stages=len(self.context_history))
        return compressed

    def _extract_key_fields(self, data: dict[str, Any], max_length: int = 200) -> dict[str, Any]:
        """
        Extract key fields and truncate long values for compression.
        
        Args:
            data: Data dictionary to compress
            max_length: Maximum string length before truncation
        
        Returns:
            Compressed dictionary
        """
        if not isinstance(data, dict):
            return {"value": str(data)[:max_length]}

        compressed = {}
        for key, value in data.items():
            if isinstance(value, str):
                compressed[key] = value[:max_length] + "..." if len(value) > max_length else value
            elif isinstance(value, (list, dict)):
                # For collections, just store count and type
                compressed[key] = f"[{type(value).__name__} with {len(value)} items]"
            else:
                compressed[key] = value

        return compressed

    def get_judge_context(self, user_intent: dict[str, Any], final_blog: str) -> dict[str, Any]:
        """
        Prepare compressed context for LLM judge.
        
        Args:
            user_intent: Original user intent/topic
            final_blog: Final blog content to judge
        
        Returns:  
            Complete judge context with compression
        """
        compressed_pipeline = self.compress_context()

        return {
            "user_intent": user_intent,
            "pipeline_context": compressed_pipeline,
            "final_blog": final_blog,
            "blog_length": len(final_blog.split()),
        }

    def reset(self) -> None:
        """Reset context history for new blog generation."""
        self.context_history = []
        logger.info("context_reset")
