"""Blog generation API routes - All requests use async queue.

NO LLM CALLS IN HTTP HANDLERS.
All blog generation is handled by background workers.
Full backpressure controls at all boundaries.
"""

import uuid
from fastapi import APIRouter, HTTPException, Header, Request
from pydantic import BaseModel, Field

from src.config.logging_config import get_logger
from src.core.backpressure import (
    api_concurrency_limiter,
    ConcurrencyLimitExceeded,
    get_all_stats as get_backpressure_stats,
)
from src.core.idempotency import idempotency_store
from src.core.task_queue import (
    enqueue_blog_generation,
    get_generation_status,
    task_queue,
    QueueFullError,
)
from src.guards.input_guard import input_guard
from src.guards.rate_limit_guard import rate_limit_guard
from src.models.repository import db_repository

logger = get_logger(__name__)

router = APIRouter()



class BlogGenerationRequest(BaseModel):
    """Blog generation request model."""

    user_id: str = Field(..., description="User identifier")
    topic: str = Field(..., min_length=10, max_length=500, description="Blog topic")
    audience: str | None = Field(None, max_length=200, description="Target audience")


class ApprovalRequest(BaseModel):
    """Approval request model."""

    session_id: str = Field(..., description="Blog session ID")
    approved: bool = Field(..., description="Whether stage is approved")
    feedback: str | None = Field(None, description="Optional feedback if not approved")


class BlogGenerationResponse(BaseModel):
    """Blog generation response - always returns immediately."""

    session_id: str
    task_id: str
    status: str = "queued"
    message: str
    poll_url: str


class TaskStatusResponse(BaseModel):
    """Async task status response."""
    
    task_id: str
    status: str
    stage: str | None = None
    progress: int | None = None
    result: dict | None = None
    error: str | None = None


class QueueStatsResponse(BaseModel):
    """Queue statistics response."""
    
    pending: int
    processing: int
    dead_letter: int


@router.post("/blog/generate", status_code=202, response_model=BlogGenerationResponse)
async def generate_blog(
    request: BlogGenerationRequest,
    req: Request,
    idempotency_key: str | None = Header(None, alias="Idempotency-Key"),
):
    """
    Initiate blog generation (async).
    
    **This endpoint returns immediately (202 Accepted).**
    
    The blog is generated by background workers. Poll `/blog/task/{task_id}` 
    for status updates.
    
    **Flow:**
    1. Concurrency check (backpressure)
    2. Request validated
    3. Blog record created in DB
    4. Job enqueued to Redis (with queue depth check)
    5. Returns task_id for polling
    
    **Backpressure:**
    - Returns 503 if API overloaded (concurrency limit)
    - Returns 503 if queue is full (queue depth limit)
    
    **Idempotency:**
    Provide `Idempotency-Key` header to prevent duplicate processing on retries.
    """
    try:
        # BACKPRESSURE: Concurrency limit for API layer
        async with api_concurrency_limiter:
            
            # Get user_id - prefer from JWT if available
            user_id = getattr(req.state, "user_id", None) or request.user_id
            
            # Check idempotency
            is_new, cached_response = await idempotency_store.check_and_set(
                user_id=user_id,
                endpoint="/blog/generate",
                idempotency_key=idempotency_key,
                request_body=request.model_dump(),
            )
            
            if not is_new:
                if cached_response:
                    logger.info("idempotency_cache_hit", user_id=user_id)
                    return BlogGenerationResponse(**cached_response)
                else:
                    raise HTTPException(
                        status_code=409,
                        detail="Request already in progress with this idempotency key",
                    )
            
            # Validate input
            valid, msg = input_guard.validate_input(request.topic, request.audience)
            if not valid:
                await idempotency_store.clear(
                    user_id=user_id,
                    endpoint="/blog/generate",
                    idempotency_key=idempotency_key,
                )
                raise HTTPException(status_code=400, detail=msg)
            
            # Check rate limits
            allowed, msg = await rate_limit_guard.check_all_limits(user_id, is_blog_request=True)
            if not allowed:
                await idempotency_store.clear(
                    user_id=user_id,
                    endpoint="/blog/generate",
                    idempotency_key=idempotency_key,
                )
                raise HTTPException(status_code=429, detail=msg)
            
            # Generate session ID
            session_id = str(uuid.uuid4())
            
            # Create blog record in DB
            await db_repository.get_or_create_user(user_id)
            blog = await db_repository.create_blog(
                user_id=user_id,
                session_id=session_id,
                topic=request.topic,
                audience=request.audience or "general readers",
            )
            
            # Enqueue job - NO LLM CALL HERE
            task_id = await enqueue_blog_generation(
                user_id=user_id,
                topic=request.topic,
                audience=request.audience,
                session_id=session_id,
                blog_id=blog.id,
            )
            
            # Update rate limiters
            await rate_limit_guard.increment_global_blog_count()
            await rate_limit_guard.increment_user_blog_count(user_id)
            
            response = BlogGenerationResponse(
                session_id=session_id,
                task_id=task_id,
                status="queued",
                message="Blog generation queued. Poll /blog/task/{task_id} for status.",
                poll_url=f"/api/v1/blog/task/{task_id}",
            )
            
            # Cache for idempotency
            await idempotency_store.set_response(
                user_id=user_id,
                endpoint="/blog/generate",
                response=response.model_dump(),
                idempotency_key=idempotency_key,
            )
            
            logger.info(
                "blog_generation_queued",
                session_id=session_id,
                task_id=task_id,
                user_id=user_id,
            )
            
            return response

        
    except ConcurrencyLimitExceeded:
        # BACKPRESSURE: API overloaded - fast fail
        logger.warning("api_concurrency_limit_exceeded", user_id=request.user_id)
        raise HTTPException(
            status_code=503,
            detail="Service temporarily overloaded. Please retry.",
            headers={"Retry-After": "5"},
        )
        
    except QueueFullError as e:
        # BACKPRESSURE: Queue at capacity - fast fail
        logger.warning("queue_full", user_id=request.user_id, detail=str(e))
        raise HTTPException(
            status_code=503,
            detail="Job queue at capacity. Please retry later.",
            headers={"Retry-After": "10"},
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error("blog_generation_failed", error=str(e))
        if idempotency_key:
            await idempotency_store.clear(
                user_id=request.user_id,
                endpoint="/blog/generate",
                idempotency_key=idempotency_key,
            )
        raise HTTPException(status_code=500, detail=f"Failed to queue blog generation: {str(e)}")



@router.get("/blog/task/{task_id}", response_model=TaskStatusResponse)
async def get_task_status(task_id: str):
    """
    Get blog generation task status.
    
    Poll this endpoint for progress updates.
    
    **Status values:**
    - `pending`: Waiting in queue
    - `processing`: Generation in progress  
    - `completed`: Done - result available
    - `failed`: Error occurred
    
    **Stages (during processing):**
    - `intent`: Analyzing topic
    - `outline`: Creating structure
    - `research`: Gathering information
    - `writing`: Generating content
    """
    try:
        status = await get_generation_status(task_id)
        
        if status is None:
            raise HTTPException(status_code=404, detail="Task not found")
        
        # Calculate progress from stage
        stage = status.get("payload", {}).get("stage", "pending")
        progress = {
            "pending": 0,
            "intent": 20,
            "outline": 40,
            "research": 60,
            "writing": 80,
            "completed": 100,
        }.get(stage, 50)
        
        if status.get("status") == "completed":
            progress = 100
        
        return TaskStatusResponse(
            task_id=task_id,
            status=status.get("status", "unknown"),
            stage=stage,
            progress=progress,
            result=status.get("result"),
            error=status.get("error"),
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error("task_status_failed", error=str(e))
        raise HTTPException(status_code=500, detail="Failed to get task status")


@router.get("/blog/status/{session_id}")
async def get_blog_status(session_id: str):
    """
    Get blog status by session ID.
    
    Alternative to task-based polling.
    """
    try:
        blog = await db_repository.get_blog_by_session(session_id)
        
        if not blog:
            raise HTTPException(status_code=404, detail="Blog not found")
        
        return {
            "session_id": session_id,
            "blog_id": blog.id,
            "status": blog.status,
            "current_stage": blog.current_stage,
            "topic": blog.topic,
            "title": blog.title,
            "word_count": blog.word_count,
            "created_at": blog.created_at.isoformat() if blog.created_at else None,
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error("status_check_failed", error=str(e))
        raise HTTPException(status_code=500, detail="Status check failed")


@router.get("/blog/content/{session_id}")
async def get_blog_content(session_id: str):
    """
    Get the final generated blog content.
    
    Only available after blog status is 'completed'.
    """
    try:
        blog = await db_repository.get_blog_by_session(session_id)
        
        if not blog:
            raise HTTPException(status_code=404, detail="Blog not found")
        
        if blog.status != "completed":
            raise HTTPException(
                status_code=400,
                detail=f"Blog not completed. Current status: {blog.status}",
            )
        
        return {
            "session_id": session_id,
            "title": blog.title,
            "content": blog.content,
            "word_count": blog.word_count,
            "sources_count": blog.sources_count,
            "topic": blog.topic,
            "audience": blog.audience,
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error("content_fetch_failed", error=str(e))
        raise HTTPException(status_code=500, detail="Failed to fetch blog content")


@router.get("/blog/queue/stats", response_model=QueueStatsResponse)
async def get_queue_stats():
    """
    Get queue statistics.
    
    Useful for monitoring and debugging.
    """
    try:
        stats = await task_queue.get_queue_stats()
        return QueueStatsResponse(**stats)
    except Exception as e:
        logger.error("queue_stats_failed", error=str(e))
        raise HTTPException(status_code=500, detail="Failed to get queue stats")


@router.get("/blog/backpressure/stats")
async def get_backpressure_status():
    """
    Get backpressure control statistics.
    
    Returns circuit breaker states and concurrency limits.
    Useful for monitoring system health under load.
    """
    try:
        queue_stats = await task_queue.get_queue_stats()
        backpressure = get_backpressure_stats()
        
        return {
            "queue": {
                **queue_stats,
                "max_depth": task_queue.MAX_QUEUE_DEPTH,
            },
            **backpressure,
        }
    except Exception as e:
        logger.error("backpressure_stats_failed", error=str(e))
        raise HTTPException(status_code=500, detail="Failed to get backpressure stats")



# Legacy endpoints for backward compatibility (deprecated)
@router.post("/blog/approve")
async def approve_stage(request: ApprovalRequest):
    """
    DEPRECATED: HITL approval is no longer supported.
    
    Blog generation now runs fully automatically via background workers.
    Use /blog/task/{task_id} to poll for completion.
    """
    raise HTTPException(
        status_code=410,  # Gone
        detail="HITL approval workflow deprecated. Blogs are now generated automatically. "
               "Poll /blog/task/{task_id} for status.",
    )
